### ISSUE TITLE
Supabase: create tables

### ISSUE THREAD

**Issue by Treimart** [rakenduste-programmeerimine-2023/learner#24]
Create the following tables for Supabase according to the following image (ignore `user` table):

![Learner-2023-11-15_20-09](https://github.com/rakenduste-programmeerimine-2023/learner/assets/114922060/ff6deb32-f2d8-41e1-afb8-d3d50292ae11)

**Comment by stellamarii** [comment]
Create all tables we need
`npx supabase migration new <table name>`
